version: '3'
services:
    backend:
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        container_name: backend
        restart: unless-stopped
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        working_dir: /var/www/center
        volumes:
            - '.:/var/www/center'
        depends_on:
            - database
    nginx:
        container_name: server
        image: 'nginx:alpine'
        restart: unless-stopped
        ports:
            - '80:80'
        volumes:
            - '.:/var/www/center'
            - './docker/nginx/conf.d/:/etc/nginx/conf.d/'
        depends_on:
            - backend
    node:
        container_name: frontend
        build:
            context: .
            dockerfile: ./docker/nodejs/Dockerfile
        ports:
            - '5173:5173'
        working_dir: /var/www/center
        volumes:
            - '.:/var/www/center'
    database:
        container_name: db
        image: 'postgres:14.5'
        environment:
            - 'POSTGRES_DB=${DB_DATABASE}'
            - 'POSTGRES_USER=${DB_USERNAME}'
            - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
        ports:
            - '${DB_PORT}:5432'
        volumes:
            - 'postgresql:/var/lib/postgresql/data/'
volumes:
    postgresql:
        driver: local
