<?php

return $for_recover_groups = [
    'visual_or_sensory_extinction' => ['Отсутствует', "Зрительное", "Сенсерное", "Присутствуют оба"],
    'swallowing' => ['Способен', "Не способен"],
    'talk' => ['Нет', "Есть"],
    'cardio_system' => ['Без патологий', "АГ", "ИБС", "Фибрилляция предсердий"],
    'stents' => [false, true],
    'hand_tactility' => [false, true],
    'hand_t' => [false, true],
    'hand_pain' => [false, true],
    'hand_musculoskeletal_feeling' => [false, true],
    'leg_tactility' => [false, true],
    'leg_t' => [false, true],
    'leg_pain' => [false, true],
    'leg_musculoskeletal_feeling' => [false, true],
    'memory_loss' => ['Отсутствует', "Кратковременная", "Долговременная"],
    'shortness' => [false, true],
    'cough' => [false, true],
    'asthma' => [false, true],
    'smoking' => [false, true],
    'SRM' => [0, 1, 2, 3, 4, 5, 6],

    'lying_turn' => [false, true],
    'sits_down' => [false, true],
    'sits' => [false, true],
    'gets_up' => [false, true],
    'to_stand' => [false, true],
    'get_up_sits_down' => [false, true],
    'helps_walking_room' => [false, true],
    'stairwell' => [false, true],
    'walking_street' => [false, true],
    'walking_room' => [false, true],
    'raise_item' => [false, true],
    'walks_gravel' => [false, true],
    'washes' => [false, true],
    'ladder' => [false, true],
    'running' => [false, true],
];
